### ISSUE TITLE
Add config check that recommends against some remoting features

### ISSUE THREAD

**Issue by patriknw** [akka/akka-diagnostics#13]
Such as:
- remote deployment
- using remoting without cluster
- remote watch failure detector (shouldn't be used when cluster is used)

**Comment by franciscolopezsancho** [comment]
To check my understanding:
- `remote deployment` means [akka.actor.deployment.default.remote](https://github.com/akka/akka/blob/2b9f051a51e48d9de281be6ff1f0059b445ffc9b/akka-remote/src/main/resources/reference.conf#L143). Setting this property is not recommended or? `akka.actor.provider = remote` is not recommended. 
-  `using remoting without cluster` means setting any `akka.actor.remote` property while `akka.actor.provider != cluster`.

**Comment by johanandren** [comment]
1. specifying `remote` in the config block for an actor means it would be deployed remotely when started, we have deprecated that and it is not supported at all in Akka Typed, so this is not about overriding the default but as shown in classic docs here: https://doc.akka.io/docs/akka/current/remoting.html#creating-actors-remotely
2. `akka.actor.provider = remote` is the "remoting without cluster" part
3. remote watch failure detector is maybe obvious but `akka.remote.watch-failure-detector`
